import "./globals.css";

export const metadata = {
	title: "Mint",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" data-theme="forest">
			<body>{children}</body>
		</html>
	);
}
