import "./globals.css";
import { Epilogue } from "next/font/google";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata = {
	title: "Mint",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" data-theme="forest" className={epilogue.className}>
			<body>{children}</body>
		</html>
	);
}
